"use client";

import { FormEvent, ReactNode, useEffect, useState } from "react";
import { citationFor, localize as localizeCatalog, type AnimalEntry, type CatalogGroup, type Locale } from "@/lib/catalog";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";
import { persistFavorite, uploadPetPhoto } from "@/lib/persistence";

type Tone = "safe" | "caution" | "avoid" | "danger" | "neutral";

const breedImages: Record<string, string> = {
  "Shiba Inu": "https://images.unsplash.com/photo-1612536057832-2ff7ead58194?auto=format&fit=crop&w=1200&q=85",
  "Golden Retriever": "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=1200&q=85",
  "Border Collie": "https://images.unsplash.com/photo-1503256207526-0d5d80fa2f47?auto=format&fit=crop&w=1200&q=85",
  "German Shepherd": "https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?auto=format&fit=crop&w=1200&q=85",
  "Siberian Husky": "https://images.unsplash.com/photo-1605568427561-40dd23c2acea?auto=format&fit=crop&w=1200&q=85",
  "Labrador Retriever": "https://images.unsplash.com/photo-1591769225440-811ad7d6eab3?auto=format&fit=crop&w=1200&q=85",
  "British Shorthair": "https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=1200&q=85",
  "Maine Coon": "https://images.unsplash.com/photo-1618826411640-d6df44dd3f7a?auto=format&fit=crop&w=1200&q=85",
  Ragdoll: "https://images.unsplash.com/photo-1606214174585-fe31582dc6ee?auto=format&fit=crop&w=1200&q=85",
  Siamese: "https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&w=1200&q=85",
};

const breeds = [
  { name: "Shiba Inu", species: "Dog", origin: "Japan", energy: 4, ease: 2, tags: "Independent · Alert · Loyal" },
  { name: "Golden Retriever", species: "Dog", origin: "Scotland", energy: 4, ease: 5, tags: "Social · Gentle · Trainable" },
  { name: "Border Collie", species: "Dog", origin: "United Kingdom", energy: 5, ease: 3, tags: "Focused · Athletic · Brilliant" },
  { name: "German Shepherd", species: "Dog", origin: "Germany", energy: 4, ease: 3, tags: "Confident · Loyal · Versatile" },
  { name: "Siberian Husky", species: "Dog", origin: "Siberia", energy: 5, ease: 2, tags: "Social · Vocal · Energetic" },
  { name: "Labrador Retriever", species: "Dog", origin: "Canada", energy: 4, ease: 5, tags: "Outgoing · Kind · Eager" },
  { name: "British Shorthair", species: "Cat", origin: "United Kingdom", energy: 2, ease: 4, tags: "Calm · Quiet · Affectionate" },
  { name: "Maine Coon", species: "Cat", origin: "United States", energy: 3, ease: 4, tags: "Gentle · Playful · Social" },
  { name: "Ragdoll", species: "Cat", origin: "United States", energy: 2, ease: 4, tags: "Relaxed · Sweet · People-loving" },
  { name: "Siamese", species: "Cat", origin: "Thailand", energy: 4, ease: 3, tags: "Vocal · Curious · Social" },
];

const foods: { name: string; category: string; dog: Tone; cat: Tone; note: string }[] = [
  { name: "Strawberry", category: "Fruit", dog: "safe", cat: "safe", note: "Plain, washed and cut into small pieces." },
  { name: "Banana", category: "Fruit", dog: "safe", cat: "caution", note: "A small occasional portion; naturally high in sugar." },
  { name: "Carrot", category: "Vegetable", dog: "safe", cat: "safe", note: "Serve plain in bite-sized pieces." },
  { name: "Chicken", category: "Meat", dog: "safe", cat: "safe", note: "Cook thoroughly; no bones, seasoning or skin." },
  { name: "Rice", category: "Grain", dog: "safe", cat: "caution", note: "Plain cooked rice can be an occasional addition." },
  { name: "Cheese", category: "Dairy", dog: "caution", cat: "caution", note: "Many pets do not tolerate lactose well." },
  { name: "Chocolate", category: "Snack", dog: "danger", cat: "danger", note: "Seek veterinary help if ingestion is suspected." },
  { name: "Grapes", category: "Fruit", dog: "danger", cat: "avoid", note: "Grapes and raisins can be dangerous to dogs." },
  { name: "Onion", category: "Ingredient", dog: "danger", cat: "danger", note: "Avoid fresh, cooked and powdered forms." },
  { name: "Garlic", category: "Ingredient", dog: "danger", cat: "danger", note: "Allium ingredients can harm cats and dogs." },
  { name: "Xylitol", category: "Ingredient", dog: "danger", cat: "avoid", note: "A veterinary emergency for dogs." },
];

const behaviorItems = ["Tail wagging", "Licking paws", "Zoomies", "Growling", "Barking", "Digging", "Staring", "Yawning", "Licking lips", "Following everywhere", "Kneading", "Purring", "Hiding", "Slow blinking", "Scratching", "Tail twitching", "Chirping", "Nighttime zoomies", "Bringing objects"];

const routeMeta: Record<string, [string, string, string, string]> = {
  "/discover": ["Discover Pawtome", "A calmer way to find the right guidance.", "Khám phá Pawtome", "Một cách rõ ràng hơn để tìm hướng dẫn phù hợp."],
  "/breeds": ["Multi-species encyclopedia", "Explore reviewed guidance for breeds, species and recognized varieties.", "Bách khoa thú cưng đa loài", "Khám phá hướng dẫn đã rà soát cho giống, loài và biến thể được công nhận."],
  "/compare": ["Compare breeds", "See meaningful differences side by side—not a winner and a loser.", "So sánh giống", "Xem những khác biệt quan trọng cạnh nhau—không xếp hạng hơn thua."],
  "/pet-match": ["Which pet fits your life?", "A thoughtful starting point, never a guarantee of individual temperament.", "Thú cưng nào hợp với bạn?", "Điểm khởi đầu hữu ích, không phải bảo đảm về tính khí từng cá thể."],
  "/food": ["Can my pet eat this?", "Clear food guidance for dogs and cats.", "Thú cưng của tôi có ăn được không?", "Hướng dẫn thực phẩm rõ ràng cho chó và mèo."],
  "/food/checker": ["Check multiple ingredients", "Paste a label or enter one ingredient per line.", "Kiểm tra nhiều thành phần", "Dán nhãn hoặc nhập mỗi thành phần trên một dòng."],
  "/training": ["Training academy", "Kind, short sessions that build skills and trust.", "Học viện huấn luyện", "Các buổi học ngắn, tích cực để xây kỹ năng và niềm tin."],
  "/behavior": ["Why does my pet do this?", "Read the whole animal: body, setting, frequency and change over time.", "Vì sao thú cưng làm vậy?", "Hãy xem toàn cảnh: cơ thể, bối cảnh, tần suất và thay đổi theo thời gian."],
  "/care": ["Build a healthy routine", "Everyday care that flexes around the pet in front of you.", "Xây dựng thói quen khỏe mạnh", "Chăm sóc hằng ngày linh hoạt theo từng thú cưng."],
  "/grooming": ["Grooming & seasonal care", "Practical routines for coat, paws, ears, teeth and changing weather.", "Chăm sóc lông & theo mùa", "Thói quen thực tế cho lông, chân, tai, răng và thời tiết thay đổi."],
  "/safety": ["Pet safety centre", "Prepare calmly. Act quickly when warning signs appear.", "Trung tâm an toàn thú cưng", "Chuẩn bị bình tĩnh. Hành động nhanh khi có dấu hiệu cảnh báo."],
  "/plants": ["Toxic plants & foods", "Search common household risks for cats and dogs.", "Cây & thực phẩm độc hại", "Tra cứu nguy cơ thường gặp trong nhà cho chó và mèo."],
  "/first-30-days": ["Your first 30 days together", "A gentle plan for safety, routine and growing trust.", "30 ngày đầu bên nhau", "Kế hoạch nhẹ nhàng cho an toàn, nề nếp và niềm tin."],
  "/ask": ["Ask Pawtome", "Clear explanations grounded in the reviewed Pawtome Care Library.", "Hỏi Pawtome", "Giải thích rõ ràng dựa trên Thư viện Chăm sóc Pawtome đã được rà soát."],
  "/my-pets": ["My pets", "A personal home for routines, progress and memories.", "Thú cưng của tôi", "Nơi riêng để lưu thói quen, tiến bộ và kỷ niệm."],
  "/saved": ["Saved for later", "Your breeds, foods, lessons and guides in one quiet place.", "Đã lưu", "Giống, thực phẩm, bài học và hướng dẫn ở một nơi."],
  "/account": ["Your Pawtome account", "Secure access to private pet profiles and progress.", "Tài khoản Pawtome", "Truy cập an toàn vào hồ sơ và tiến độ riêng tư."],
};

function localized(locale: Locale, english: string, vietnamese: string) {
  if (locale === "vi") return vietnamese;
  if (locale === "en-GB") {
    return english
      .replaceAll("Behavior", "Behaviour")
      .replaceAll("behavior", "behaviour")
      .replaceAll("Personalized", "Personalised")
      .replaceAll("personalized", "personalised")
      .replaceAll("center", "centre")
      .replaceAll("Center", "Centre");
  }
  return english;
}

function Stars({ value }: { value: number }) {
  void value;
  return <span className="stars" aria-label="Needs evidence review">—</span>;
  /* ponytail: keep the legacy rating source inert until each value has evidence.
  return <span className="stars" aria-label={`${value} out of 5`}>{"★".repeat(value)}{"☆".repeat(5 - value)}</span>;
  */
}

function Status({ tone, children }: { tone: Tone; children?: ReactNode }) {
  const label = children || ({ safe: "Generally safe", caution: "Use with caution", avoid: "Avoid", danger: "Dangerous", neutral: "Guidance" }[tone]);
  return <span className={`status ${tone}`}><span aria-hidden="true">{{ safe: "✓", caution: "!", avoid: "–", danger: "!", neutral: "i" }[tone]}</span>{label}</span>;
}

function Section({ eyebrow, title, intro, children, className = "" }: { eyebrow?: string; title: string; intro?: string; children: ReactNode; className?: string }) {
  return <section className={`section ${className}`}>
    <div className="section-head">{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2>{intro && <p>{intro}</p>}</div>
    {children}
  </section>;
}

function BreedCard({ breed, locale, saved, toggle }: { breed: typeof breeds[number]; locale: Locale; saved: boolean; toggle: () => void }) {
  return <article className="breed-card">
    <a className="image-link" href={breed.name === "Shiba Inu" ? "/breeds/shiba-inu" : "/breeds"}>
      <img src={breedImages[breed.name]} alt={`${breed.name} ${breed.species.toLowerCase()}`} />
    </a>
    <button className={`save ${saved ? "active" : ""}`} aria-label={saved ? "Remove from saved" : "Save breed"} onClick={toggle}>{saved ? "♥" : "♡"}</button>
    <div className="card-body"><span className="kicker">{breed.species} · {breed.origin}</span><h3>{breed.name}</h3><p>{breed.tags}</p>
      <div className="ratings"><span>{localized(locale, "Energy", "Năng lượng")} <Stars value={breed.energy} /></span><span>{localized(locale, "Beginner", "Người mới")} <Stars value={breed.ease} /></span></div>
    </div>
  </article>;
}

const groupLabels: Record<CatalogGroup, [string, string]> = {
  dog: ["Dog breed", "Giống chó"], cat: ["Cat breed", "Giống mèo"], bird: ["Bird species / variety", "Loài / biến thể chim"],
  "small-mammal": ["Rabbit / small mammal", "Thỏ / thú nhỏ"], reptile: ["Reptile species", "Loài bò sát"], "freshwater-fish": ["Freshwater fish", "Cá nước ngọt"],
};

function CatalogCard({ entry, locale, saved, toggle }: { entry: AnimalEntry; locale: Locale; saved: boolean; toggle: () => void }) {
  const l = (en: string, vi: string) => localized(locale, en, vi);
  return <article className="breed-card catalog-card">
    <a className="image-link catalog-image" href={`/breeds/${entry.slug}`}>
      <img src={entry.imageUrl} alt={localizeCatalog(entry.imageAlt, locale)} onError={e => { e.currentTarget.src = "/brand/pawtome-logo.png"; }} />
    </a>
    <button className={`save ${saved ? "active" : ""}`} aria-label={saved ? l("Remove from saved", "Bỏ lưu") : l("Save entry", "Lưu mục này")} onClick={toggle}>{saved ? "♥" : "♡"}</button>
    <div className="card-body">
      <span className="kicker">{l(...groupLabels[entry.group])}{entry.origin ? ` · ${entry.origin}` : ""}</span>
      <h3>{localizeCatalog(entry.commonName, locale)}</h3>
      <p><i>{entry.scientificName}</i></p>
      <div className="catalog-tags"><Status tone="neutral">{l(`${entry.activity} activity`, `Vận động: ${entry.activity}`)}</Status><Status tone={entry.reviewStatus === "needs-entry-review" ? "caution" : "safe"}>{entry.reviewStatus === "needs-entry-review" ? l("Needs entry review", "Cần rà soát riêng") : l("Reviewed", "Đã rà soát")}</Status></div>
    </div>
  </article>;
}

function EvidenceSection({ entry, locale }: { entry: AnimalEntry; locale: Locale }) {
  const l = (en: string, vi: string) => localized(locale, en, vi);
  const sources = entry.citationIds.map(citationFor).filter(Boolean);
  return <Section eyebrow={l("Traceable evidence", "Bằng chứng có thể truy vết")} title={l("Sources and review status", "Nguồn và trạng thái rà soát")} intro={l("Each source supports a named general claim. Entry-specific health, lifespan and precise ratings remain unset until separately reviewed.", "Mỗi nguồn hỗ trợ một khẳng định chung được nêu rõ. Sức khỏe riêng, tuổi thọ và điểm số chính xác vẫn để trống đến khi được rà soát riêng.")}>
    <div className="evidence-list container">{sources.map(source => source && <article key={source.id}><div><Status tone="neutral">{source.evidenceType.replaceAll("-", " ")}</Status><Status tone="safe">{source.evidenceStrength.replaceAll("-", " ")}</Status></div><h3><a href={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a></h3><p>{source.authorsOrOrganization} · {source.publicationYear ?? l("Year not stated", "Không nêu năm")} · {source.journalOrPublisher}</p><p><b>{l("Supported claim:", "Khẳng định được hỗ trợ:")}</b> {source.supportedClaim}</p><p className="fineprint"><b>{l("Limit:", "Giới hạn:")}</b> {source.limitations}</p></article>)}</div>
    <p className="container fineprint">{l(`Last reviewed ${entry.reviewedAt}. Pawtome provides general education and does not replace veterinary assessment.`, `Rà soát lần cuối ${entry.reviewedAt}. Pawtome cung cấp kiến thức chung và không thay thế đánh giá thú y.`)}</p>
  </Section>;
}

function AnimalDetail({ entry, locale }: { entry: AnimalEntry; locale: Locale }) {
  const l = (en: string, vi: string) => localized(locale, en, vi);
  const facts = [[l("Origin", "Nguồn gốc"), entry.origin ?? l("Needs review", "Cần rà soát")], [l("Size", "Kích thước"), entry.size ?? l("Needs review", "Cần rà soát")], [l("Expected lifespan", "Tuổi thọ dự kiến"), entry.lifespan ?? l("Needs review", "Cần rà soát")]];
  const guidance = [[l("Housing & environment", "Nơi ở & môi trường"), entry.housing], [l("Feeding overview", "Tổng quan ăn uống"), entry.feeding], [l("Activity & enrichment", "Vận động & làm giàu"), entry.enrichment], [l("Social needs", "Nhu cầu xã hội"), entry.socialNeeds], [l("Maintenance", "Chăm sóc định kỳ"), entry.maintenance], [l("Training", "Huấn luyện"), entry.training], [l("Welfare considerations", "Cân nhắc phúc lợi"), entry.welfare], [l("Health boundary", "Ranh giới sức khỏe"), entry.health], [l("Children & other pets", "Trẻ em & thú khác"), entry.suitability], [l("Climate sensitivity", "Nhạy cảm khí hậu"), entry.climateSensitivity]] as const;
  return <main><section className="breed-detail-hero container"><div className="breed-detail-image"><img src={entry.imageUrl} alt={localizeCatalog(entry.imageAlt, locale)} onError={e => { e.currentTarget.src = "/brand/pawtome-logo.png"; }} /></div><div><p className="eyebrow">{l(...groupLabels[entry.group])}</p><h1>{localizeCatalog(entry.commonName, locale)}</h1><p className="lede">{localizeCatalog(entry.summary, locale)}</p><p><i>{entry.scientificName}</i></p><div className="facts">{facts.map(([label,value])=><span key={label}><small>{label}</small><b>{value}</b></span>)}</div><Status tone="caution">{l("Broad guidance · individual assessment required", "Hướng dẫn chung · cần đánh giá từng cá thể")}</Status></div></section>
    <Section title={l("Care overview", "Tổng quan chăm sóc")} intro={l("Unknown fields stay unknown; the catalog does not turn weak evidence into precise ratings.", "Trường chưa biết vẫn để chưa biết; danh mục không biến bằng chứng yếu thành điểm số chính xác.")}><div className="guidance-grid catalog-guidance container">{guidance.map(([title,value])=><article key={title}><h2>{title}</h2><p>{localizeCatalog(value, locale)}</p></article>)}</div></Section>
    <EvidenceSection entry={entry} locale={locale} />
  </main>;
}

function PageHero({ locale, route, tag }: { locale: Locale; route: string; tag?: string }) {
  const meta = routeMeta[route] || ["Pawtome guide", "Practical guidance for life together.", "Hướng dẫn Pawtome", "Chỉ dẫn thực tế cho cuộc sống bên nhau."];
  return <header className="page-hero container"><p className="eyebrow">{tag || localized(locale, "Pawtome Care Library", "Thư viện Chăm sóc Pawtome")}</p><h1>{localized(locale, meta[0], meta[2])}</h1><p>{localized(locale, meta[1], meta[3])}</p></header>;
}

function Home({ locale, saved, toggleSaved }: { locale: Locale; saved: string[]; toggleSaved: (s: string) => void }) {
  const l = (en: string, vi: string) => localized(locale, en, vi);
  const tools = [
    ["01", l("Explore Breeds", "Khám phá giống"), l("Compare temperament, care and lifestyle fit.", "So sánh tính khí, chăm sóc và mức độ phù hợp."), "/breeds"],
    ["02", l("Can My Pet Eat This?", "Thú cưng ăn được không?"), l("Check food safety in seconds.", "Kiểm tra an toàn thực phẩm trong vài giây."), "/food"],
    ["03", l("Why Does My Pet Do This?", "Vì sao thú cưng làm vậy?"), l("Understand behavior in context.", "Hiểu hành vi trong đúng bối cảnh."), "/behavior"],
    ["04", l("Training Academy", "Học viện huấn luyện"), l("Build skills through kind, short practice.", "Xây kỹ năng qua các bài tập ngắn, tích cực."), "/training"],
  ];
  return <>
    <section className="hero container">
      <div className="hero-copy"><p className="eyebrow">{l("Understand. Care. Grow Together.", "Thấu hiểu. Chăm sóc. Cùng trưởng thành.")}</p><h1>{l("Understand your pet better. Care for them smarter.", "Hiểu thú cưng sâu hơn. Chăm sóc thông minh hơn.")}</h1><p>{l("Discover breeds, decode behavior, check safe foods and build better daily routines for the animals you love.", "Khám phá giống, hiểu hành vi, kiểm tra thực phẩm an toàn và xây dựng thói quen tốt hơn cho thú cưng bạn yêu.")}</p>
        <div className="actions"><a className="button primary" href="/discover">{l("Explore pets", "Khám phá thú cưng")}</a><a className="button secondary" href="/pet-match">{l("Find my ideal pet", "Tìm thú cưng phù hợp")}</a></div>
        <a href="/ask" className="smart-search"><span aria-hidden="true">⌕</span><span><b>{l("What would you like to know?", "Bạn muốn biết điều gì?")}</b><small>{l("Try “Can dogs eat strawberries?”", "Thử “Chó có ăn được dâu tây không?”")}</small></span><span aria-hidden="true">→</span></a>
      </div>
      <div className="hero-visual"><img src="https://images.unsplash.com/photo-1652908452131-311e865e806b?auto=format&fit=crop&w=1400&q=90" alt={l("A dog and cat relaxing together on a sofa", "Một chú chó và mèo thư giãn cùng nhau trên ghế sofa")} /><div className="floating-note"><span>●</span><b>{l("Guidance that sees the whole pet", "Hướng dẫn nhìn toàn diện từng thú cưng")}</b></div></div>
    </section>
    <section className="tool-grid container" aria-label={l("Pawtome tools", "Công cụ Pawtome")}>{tools.map(([n, title, desc, href]) => <a href={href} className="tool-card" key={title}><span>{n}</span><h2>{title}</h2><p>{desc}</p><b aria-hidden="true">↗</b></a>)}</section>
    <Section eyebrow={l("Breed discovery", "Khám phá giống")} title={l("Meet popular breeds", "Gặp gỡ các giống phổ biến")} intro={l("General tendencies are a starting point. Every animal is an individual.", "Khuynh hướng chung chỉ là điểm khởi đầu. Mỗi thú cưng là một cá thể riêng.")}>
      <div className="breed-grid container">{breeds.slice(0, 6).map(b => <BreedCard key={b.name} breed={b} locale={locale} saved={saved.includes(b.name)} toggle={() => toggleSaved(b.name)} />)}</div>
    </Section>
    <section className="trust-band"><div className="container trust-grid"><div><p className="eyebrow">{l("Our information model", "Mô hình thông tin")}</p><h2>{l("Useful guidance, with clear boundaries.", "Hướng dẫn hữu ích, với ranh giới rõ ràng.")}</h2></div><div className="trust-steps"><span>{l("Reviewed knowledge", "Kiến thức đã rà soát")}</span><b>→</b><span>{l("Your pet’s context", "Bối cảnh thú cưng")}</span><b>→</b><span>{l("Clear explanation", "Giải thích rõ ràng")}</span></div></div></section>
    <Section eyebrow={l("Learn in a minute", "Học trong một phút")} title={l("Myth, meet context.", "Lầm tưởng, hãy nhìn vào bối cảnh.")}><div className="editorial-pair container"><div className="myth"><span>MYTH</span><h3>{l("A wagging tail always means a happy dog.", "Vẫy đuôi luôn có nghĩa là chó đang vui.")}</h3></div><div className="fact"><span>FACT</span><h3>{l("Tail movement has several meanings. Read it with posture, facial tension and context.", "Chuyển động đuôi có nhiều ý nghĩa. Hãy xem cùng tư thế, nét mặt và bối cảnh.")}</h3></div></div></Section>
  </>;
}

function Discover({ locale }: { locale: Locale }) {
  const l = (en: string, vi: string) => localized(locale, en, vi);
  return <><PageHero locale={locale} route="/discover" /><main className="container feature-stack">
    {[ ["Breeds", "Choose with open eyes", "Compare energy, grooming and family fit.", "/breeds"], ["Food", "Make the bowl safer", "Check everyday ingredients and urgent risks.", "/food"], ["Training", "Practice progress, not perfection", "Small lessons with clear stopping points.", "/training"], [l("Behavior", "Hành vi"), l("Notice the whole picture", "Nhìn toàn cảnh"), l("Explore body language, context and change over time.", "Khám phá ngôn ngữ cơ thể, bối cảnh và thay đổi theo thời gian."), "/behavior"] ].map((x, i) => <a href={x[3]} className="feature-row" key={x[0]}><span>0{i + 1}</span><div><p className="eyebrow">{x[0]}</p><h2>{x[1]}</h2><p>{x[2]}</p></div><b>→</b></a>)}
    <div className="quiz-card"><div><Status tone="neutral">{l("Knowledge check", "Kiểm tra kiến thức")}</Status><h2>{l("Can dogs eat grapes?", "Chó có ăn được nho không?")}</h2><p>{l("Choose an answer to reveal the guidance.", "Chọn câu trả lời để xem hướng dẫn.")}</p></div><Quiz locale={locale} /></div>
  </main></>;
}

function Quiz({ locale }: { locale: Locale }) {
  const [answer, setAnswer] = useState("");
  const l = (en: string, vi: string) => localized(locale, en, vi);
  return <div className="answer-grid">{[l("Yes", "Có"), l("Only a little", "Chỉ một chút"), l("No", "Không")].map((x, i) => <button key={x} className={answer ? (i === 2 ? "correct" : "muted") : ""} onClick={() => setAnswer(String(i))}>{x}</button>)}{answer && <p className="answer-note">{l("Correct answer: No. Grapes and raisins can be dangerous to dogs; contact a veterinarian promptly if ingestion is suspected.", "Đáp án đúng: Không. Nho tươi và nho khô có thể nguy hiểm với chó; hãy liên hệ bác sĩ thú y sớm nếu nghi ngờ đã ăn phải.")}</p>}</div>;
}

function Breeds({ locale, saved, toggleSaved, entries, source, warning }: { locale: Locale; saved: string[]; toggleSaved: (s: string) => void; entries: AnimalEntry[]; source: "supabase" | "seed"; warning: string | null }) {
  const l = (en: string, vi: string) => localized(locale, en, vi);
  const [query, setQuery] = useState("");
  const [species, setSpecies] = useState<"all" | CatalogGroup>("all");
  const [activity, setActivity] = useState("all");
  const shown = entries.filter(entry => (species === "all" || entry.group === species) && (activity === "all" || entry.activity === activity) && `${entry.commonName["en-US"]} ${entry.commonName.vi} ${entry.scientificName}`.toLowerCase().includes(query.toLowerCase()));
  const speciesOptions: Array<["all" | CatalogGroup,string,string]> = [["all","All","Tất cả"],["dog","Dogs","Chó"],["cat","Cats","Mèo"],["bird","Birds","Chim"],["small-mammal","Small mammals","Thú nhỏ"],["reptile","Reptiles","Bò sát"],["freshwater-fish","Fish","Cá"]];
  return <><PageHero locale={locale} route="/breeds" /><main className="container"><div className="data-notice"><Status tone={source === "supabase" ? "safe" : "neutral"}>{source === "supabase" ? l("Live reviewed catalog", "Danh mục trực tiếp đã rà soát") : l("Deterministic local catalog", "Danh mục cục bộ xác định")}</Status><span>{entries.length} {l("entries", "mục")}</span>{warning && <span role="status">{warning}</span>}</div><div className="filter-bar catalog-filter"><label><span>{l("Search catalog", "Tìm danh mục")}</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder={l("Name or scientific name…", "Tên thường hoặc tên khoa học…")} /></label><div className="segmented species-segments" aria-label={l("Species filter", "Lọc loài")}>{speciesOptions.map(([value,en,vi]) => <button className={species === value ? "active" : ""} onClick={() => setSpecies(value)} key={value}>{l(en,vi)}</button>)}</div><label><span>{l("Activity", "Vận động")}</span><select value={activity} onChange={e=>setActivity(e.target.value)}><option value="all">{l("All levels", "Mọi mức")}</option><option value="low">{l("Low", "Thấp")}</option><option value="moderate">{l("Moderate", "Vừa")}</option><option value="high">{l("High", "Cao")}</option></select></label></div>{shown.length ? <div className="breed-grid">{shown.map(entry => <CatalogCard key={entry.slug} entry={entry} locale={locale} saved={saved.includes(entry.slug)} toggle={() => toggleSaved(entry.slug)} />)}</div> : <div className="empty-state"><p>{l("No entries match these filters.", "Không có mục nào phù hợp bộ lọc.")}</p></div>}</main></>;
}

function Shiba({ locale, saved, toggleSaved }: { locale: Locale; saved: string[]; toggleSaved: (s: string) => void }) {
  const l = (en: string, vi: string) => localized(locale, en, vi);
  const ratings = [["Energy", "Năng lượng", 4], ["Trainability", "Dễ huấn luyện", 3], ["Grooming", "Chăm sóc lông", 3], ["Sociability", "Hòa đồng", 3], ["Independence", "Độc lập", 5], ["Family friendly", "Thân thiện gia đình", 4], ["Apartment fit", "Hợp căn hộ", 4], ["Shedding", "Rụng lông", 4]] as const;
  return <main><section className="breed-detail-hero container"><div className="breed-detail-image"><img src={breedImages["Shiba Inu"]} alt="Shiba Inu" /><button className={`save large ${saved.includes("Shiba Inu") ? "active" : ""}`} onClick={() => toggleSaved("Shiba Inu")}>{saved.includes("Shiba Inu") ? "♥" : "♡"}</button></div><div><p className="eyebrow">{l("Breed guide · Dog · Japan", "Hướng dẫn giống · Chó · Nhật Bản")}</p><h1>Shiba Inu</h1><p className="lede">{l("A compact, observant companion with a bold inner life and a famously independent point of view.", "Người bạn nhỏ gọn, tinh ý với nội tâm mạnh mẽ và tính độc lập nổi tiếng.")}</p><div className="facts"><span><small>{l("Lifespan", "Tuổi thọ")}</small><b>12–15 {l("years", "năm")}</b></span><span><small>{l("Size", "Kích thước")}</small><b>{l("Small–medium", "Nhỏ–vừa")}</b></span><span><small>{l("Group", "Nhóm")}</small><b>{l("Companion / spitz", "Bầu bạn / spitz")}</b></span></div><p>{l("Independent · Alert · Intelligent · Loyal", "Độc lập · Cảnh giác · Thông minh · Trung thành")}</p></div></section>
    <Section eyebrow={l("General breed tendencies", "Khuynh hướng chung của giống")} title={l("The Shiba at a glance", "Tổng quan về Shiba")} intro={l("These indicators describe broad patterns, not precise measurements or predictions for an individual dog.", "Các chỉ số mô tả xu hướng rộng, không phải phép đo chính xác hay dự đoán cho từng cá thể.")}><div className="rating-panel container">{ratings.map(([en, vi, n]) => <div className="metric" key={en}><div><b>{l(en, vi)}</b><span>{n}/5</span></div><div className="bar"><i style={{ width: `${n * 20}%` }} /></div></div>)}</div></Section>
    <Section title={l("What makes a Shiba unique?", "Điều gì làm Shiba đặc biệt?")}><div className="trait-grid container">{[["Fox-like face", "Gương mặt giống cáo"], ["Curled tail", "Đuôi cuộn"], ["Independent mind", "Tính cách độc lập"], ["Double coat", "Lông hai lớp"], ["Strong prey drive", "Bản năng săn đuổi mạnh"], ["Famous Shiba scream", "Tiếng “Shiba scream” nổi tiếng"], ["Naturally clean", "Tự nhiên sạch sẽ"]].map(x => <article key={x[0]}><span aria-hidden="true">✦</span><h3>{l(x[0], x[1])}</h3></article>)}</div></Section>
    <section className="fit-section"><div className="container"><div className="section-head"><p className="eyebrow">{l("Is this breed right for me?", "Giống này có hợp với tôi?")}</p><h2>{l("Love the whole Shiba—not just the look.", "Hãy yêu cả tính cách Shiba—không chỉ vẻ ngoài.")}</h2></div><div className="fit-grid"><article><h3>✓ {l("Great fit if you…", "Phù hợp nếu bạn…")}</h3><ul><li>{l("enjoy active walks", "thích đi bộ năng động")}</li><li>{l("appreciate independent pets", "trân trọng thú cưng độc lập")}</li><li>{l("can train consistently", "có thể huấn luyện nhất quán")}</li><li>{l("accept seasonal shedding", "chấp nhận rụng lông theo mùa")}</li></ul></article><article><h3>! {l("Think carefully if you…", "Cân nhắc kỹ nếu bạn…")}</h3><ul><li>{l("expect effortless obedience", "mong chờ vâng lời dễ dàng")}</li><li>{l("need immediate off-leash recall", "cần gọi về không dây dắt ngay")}</li><li>{l("strongly dislike shedding", "rất không thích rụng lông")}</li><li>{l("keep small prey animals", "nuôi động vật nhỏ dễ bị săn đuổi")}</li></ul></article></div><a className="button primary" href="/pet-match">{l("Take the pet match quiz", "Làm bài kiểm tra phù hợp")}</a></div></section>
  </main>;
}
void Shiba;

function Compare({ locale }: { locale: Locale }) {
  const l = (en: string, vi: string) => localized(locale, en, vi);
  const rows = [["Size", "Kích thước", "Small–medium", "Large", "Medium"], ["Daily exercise", "Vận động hằng ngày", "60–90 min", "60–120 min", "90–150 min"], ["Grooming", "Chăm sóc lông", "Moderate", "Moderate", "Low–moderate"], ["Shedding", "Rụng lông", "High seasonal", "Moderate–high", "Moderate"], ["Trainability", "Dễ huấn luyện", "3 / 5", "5 / 5", "5 / 5"], ["Independence", "Độc lập", "5 / 5", "2 / 5", "3 / 5"], ["Family fit", "Hợp gia đình", "4 / 5", "5 / 5", "4 / 5"], ["Apartment fit", "Hợp căn hộ", "4 / 5", "3 / 5", "2 / 5"], ["Experience", "Kinh nghiệm", "Intermediate", "Beginner", "Experienced"], ["Lifespan", "Tuổi thọ", "12–15 years", "10–12 years", "12–15 years"]];
  return <><PageHero locale={locale} route="/compare" /><main className="container"><div className="compare-picks">{["Shiba Inu", "Golden Retriever", "Border Collie"].map((x, i) => <article key={x}><img src={breedImages[x]} alt={x} /><small>{l("Breed", "Giống")} {i + 1}</small><select defaultValue={x}>{breeds.filter(b => b.species === "Dog").map(b => <option key={b.name}>{b.name}</option>)}</select></article>)}</div><div className="table-wrap"><table><thead><tr><th>{l("Characteristic", "Đặc điểm")}</th><th>Shiba Inu</th><th>Golden Retriever</th><th>Border Collie</th></tr></thead><tbody>{rows.map(r => <tr key={r[0]}><th>{l(r[0], r[1])}</th><td>{r[2]}</td><td className={r[0] === "Trainability" || r[0] === "Family fit" ? "highlight" : ""}>{r[3]}</td><td className={r[0] === "Daily exercise" ? "highlight" : ""}>{r[4]}</td></tr>)}</tbody></table></div><p className="fineprint">{l("Breed traits are broad tendencies. Early experience, health, learning history and the individual animal matter.", "Đặc điểm giống là xu hướng rộng. Trải nghiệm sớm, sức khỏe, lịch sử học tập và từng cá thể đều quan trọng.")}</p></main></>;
}

function PetMatch({ locale }: { locale: Locale }) {
  const l = (en: string, vi: string) => localized(locale, en, vi);
  const questions = [["Your home", "Nhà của bạn", ["Apartment", "House with garden", "Shared home"]], ["Activity", "Mức vận động", ["Relaxed", "Moderate", "Very active"]], ["Pet experience", "Kinh nghiệm nuôi", ["First pet", "Some experience", "Very experienced"]], ["Grooming time", "Thời gian chăm lông", ["Minimal", "Weekly", "Happy to groom often"]], ["Time alone", "Thời gian ở một mình", ["Rarely", "A few hours", "Most of the workday"]], ["Personality", "Tính cách", ["Affectionate", "Balanced", "Independent"]]] as const;
  const [step, setStep] = useState(0); const [answers, setAnswers] = useState<string[]>([]);
  if (step >= questions.length) return <><PageHero locale={locale} route="/pet-match" /><main className="container result-card"><div className="match-photo"><img src={breedImages["Golden Retriever"]} alt="Golden Retriever" /><strong>88%</strong></div><div><p className="eyebrow">{l("Your strongest match", "Mức phù hợp cao nhất")}</p><h2>Golden Retriever</h2><h3>{l("Why it fits", "Vì sao phù hợp")}</h3><p>{l("Social, family-friendly and highly trainable. Your answers suggest you can offer the daily activity and companionship this breed often enjoys.", "Hòa đồng, thân thiện gia đình và dễ huấn luyện. Câu trả lời cho thấy bạn có thể đáp ứng vận động và sự đồng hành giống này thường cần.")}</p><h3>{l("Consider", "Cần cân nhắc")}</h3><p>{l("Daily exercise, regular brushing and moderate-to-high shedding.", "Vận động hằng ngày, chải lông đều và mức rụng lông vừa đến cao.")}</p><button className="button secondary" onClick={() => { setStep(0); setAnswers([]); }}>{l("Retake quiz", "Làm lại")}</button></div></main></>;
  const q = questions[step];
  return <><PageHero locale={locale} route="/pet-match" /><main className="container quiz-shell"><div className="quiz-progress"><span style={{ width: `${((step + 1) / questions.length) * 100}%` }} /></div><p>{l("Question", "Câu")} {step + 1} / {questions.length}</p><h2>{l(q[0], q[1])}</h2><div className="choice-list">{q[2].map((x, i) => <button key={x} onClick={() => { setAnswers([...answers, x]); setStep(step + 1); }}><span>{String.fromCharCode(65 + i)}</span>{x}</button>)}</div><p className="fineprint">{l("Your result is a conversation starter, not an adoption decision.", "Kết quả là điểm khởi đầu để tìm hiểu, không phải quyết định nhận nuôi.")}</p></main></>;
}

function Food({ locale }: { locale: Locale }) {
  const l = (en: string, vi: string) => localized(locale, en, vi); const [query, setQuery] = useState("");
  const shown = foods.filter(f => f.name.toLowerCase().includes(query.toLowerCase()));
  return <><PageHero locale={locale} route="/food" /><main className="container"><div className="food-search"><span aria-hidden="true">⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder={l("Search strawberry, chicken, chocolate…", "Tìm dâu tây, thịt gà, sô-cô-la…")} /></div><div className="category-row">{["Fruits", "Vegetables", "Meat", "Dairy", "Grains", "Nuts", "Snacks", "Herbs", "Drinks", "Ingredients"].map(x => <button key={x}>{x}</button>)}</div><div className="food-layout"><div className="food-list">{shown.map(f => <a href={f.name === "Strawberry" ? "/food/strawberry" : "/food"} key={f.name} className="food-row"><div className={`food-icon ${f.dog}`}>{f.name.slice(0, 1)}</div><div><h3>{f.name}</h3><p>{f.category} · {f.note}</p></div><div><small>{l("Dogs", "Chó")}</small><Status tone={f.dog} /></div><div><small>{l("Cats", "Mèo")}</small><Status tone={f.cat} /></div><b>→</b></a>)}</div><aside className="checker-promo"><p className="eyebrow">{l("Ingredient checker", "Kiểm tra thành phần")}</p><h2>{l("Checking a whole label?", "Cần kiểm tra cả nhãn?")}</h2><p>{l("Paste multiple ingredients and spot concerns quickly.", "Dán nhiều thành phần để nhanh chóng phát hiện nguy cơ.")}</p><a className="button secondary" href="/food/checker">{l("Check ingredients", "Kiểm tra thành phần")}</a></aside></div></main></>;
}

function Strawberry({ locale }: { locale: Locale }) {
  const l = (en: string, vi: string) => localized(locale, en, vi);
  return <><header className="food-detail-hero container"><div className="fruit-orb">🍓</div><div><p className="eyebrow">{l("Food guide · Fruit", "Hướng dẫn thực phẩm · Trái cây")}</p><h1>{l("Strawberry", "Dâu tây")}</h1><p>{l("A sweet occasional treat when served plain and prepared safely.", "Món ăn vặt ngọt thỉnh thoảng khi dùng nguyên chất và chuẩn bị an toàn.")}</p></div></header><main className="container"><div className="pet-status-grid"><article><div><b>{l("For dogs", "Cho chó")}</b><Status tone="safe" /></div><p>{l("Generally safe in small amounts. Treats should stay a small part of the daily diet.", "Thường an toàn với lượng nhỏ. Đồ ăn vặt chỉ nên chiếm phần nhỏ trong khẩu phần hằng ngày.")}</p></article><article><div><b>{l("For cats", "Cho mèo")}</b><Status tone="safe" /></div><p>{l("Generally safe, but nutritionally unnecessary. Some cats may not be interested.", "Thường an toàn nhưng không cần thiết về dinh dưỡng. Một số mèo có thể không thích.")}</p></article></div><div className="guidance-grid"><article><h2>✓ {l("Prepare safely", "Chuẩn bị an toàn")}</h2><ul><li>{l("Wash thoroughly", "Rửa kỹ")}</li><li>{l("Remove leaves and stem", "Bỏ lá và cuống")}</li><li>{l("Cut into small portions", "Cắt miếng nhỏ")}</li><li>{l("Introduce gradually", "Cho thử từ từ")}</li></ul></article><article><h2>× {l("Avoid", "Tránh")}</h2><ul><li>{l("Strawberry syrup", "Xi-rô dâu")}</li><li>{l("Chocolate-covered fruit", "Trái cây phủ sô-cô-la")}</li><li>{l("Products containing xylitol", "Sản phẩm chứa xylitol")}</li><li>{l("Large portions", "Khẩu phần lớn")}</li></ul></article></div><div className="review-note"><Status tone="neutral">{l("Pawtome Guidance", "Hướng dẫn Pawtome")}</Status><p>{l("Based on the reviewed Pawtome Care Library. If your pet has a medical condition or ate a concerning product, contact a veterinary professional.", "Dựa trên Thư viện Chăm sóc Pawtome đã rà soát. Nếu thú cưng có bệnh nền hoặc ăn phải sản phẩm đáng lo, hãy liên hệ chuyên gia thú y.")}</p></div></main></>;
}

function IngredientChecker({ locale }: { locale: Locale }) {
  const l = (en: string, vi: string) => localized(locale, en, vi); const [text, setText] = useState("Chicken\nRice\nCarrot\nOnion powder"); const [checked, setChecked] = useState(false);
  const lines = text.split(/\n|,/).map(x => x.trim()).filter(Boolean);
  const toneFor = (x: string): Tone => /onion|garlic|xylitol|chocolate|grape|raisin/i.test(x) ? "danger" : /cheese|milk|salt/i.test(x) ? "caution" : "safe";
  return <><PageHero locale={locale} route="/food/checker" /><main className="container checker-shell"><section><label htmlFor="ingredients">{l("Ingredients", "Thành phần")}</label><textarea id="ingredients" value={text} onChange={e => { setText(e.target.value); setChecked(false); }} /><button className="button primary" onClick={() => setChecked(true)}>{l("Check ingredients", "Kiểm tra thành phần")}</button><p className="fineprint">{l("This screening tool does not replace professional veterinary advice.", "Công cụ sàng lọc này không thay thế tư vấn thú y chuyên môn.")}</p></section><section className="checker-results"><p className="eyebrow">{l("Results", "Kết quả")}</p>{checked ? lines.map(x => <div className="ingredient-result" key={x}><b>{x}</b><Status tone={toneFor(x)} /></div>) : <div className="empty-state">{l("Your ingredient results will appear here.", "Kết quả thành phần sẽ xuất hiện ở đây.")}</div>}{checked && lines.some(x => toneFor(x) === "danger") && <div className="urgent-note"><b>{l("Concern found", "Phát hiện nguy cơ")}</b><p>{l("Do not feed this product. If it was already eaten, contact a veterinarian or animal poison service promptly.", "Không cho ăn sản phẩm này. Nếu đã ăn, hãy liên hệ bác sĩ thú y hoặc dịch vụ chống độc động vật ngay.")}</p></div>}</section></main></>;
}

function Training({ locale }: { locale: Locale }) {
  const l = (en: string, vi: string) => localized(locale, en, vi);
  const groups = [["Puppy foundations", "Nền tảng chó con", ["Name recognition", "Sit", "Stay", "Come", "Leave it", "Drop it", "Toilet training", "Crate training"]], ["Walking", "Đi bộ", ["Loose-leash walking", "Heel", "Waiting at doors", "Recall"]], ["Behavior skills", "Kỹ năng hành vi", ["Jumping", "Barking", "Biting", "Resource guarding", "Separation training"]]] as const;
  return <><PageHero locale={locale} route="/training" /><main className="container academy"><div className="academy-feature"><div><Status tone="neutral">{l("Continue learning", "Tiếp tục học")}</Status><h2>{l("Teach your dog to sit", "Dạy chó ngồi")}</h2><p>{l("Beginner · 3–5 minutes · Treats", "Cơ bản · 3–5 phút · Đồ thưởng")}</p><div className="progress"><span style={{ width: "70%" }} /></div><small>7 / 10 {l("successful attempts", "lần thành công")}</small><a className="button primary" href="/training/sit">{l("Continue lesson", "Tiếp tục bài học")}</a></div><img src={breedImages["Golden Retriever"]} alt="Golden Retriever learning with a handler" /></div><div className="lesson-groups">{groups.map(g => <section key={g[0]}><h2>{l(g[0], g[1])}</h2><div className="lesson-grid">{g[2].map((x, i) => <a href={x === "Sit" ? "/training/sit" : "/training"} key={x}><span>{String(i + 1).padStart(2, "0")}</span><div><h3>{x}</h3><p>{l("Short guided lesson", "Bài học ngắn có hướng dẫn")}</p></div><b>→</b></a>)}</div></section>)}</div></main></>;
}

function SitLesson({ locale }: { locale: Locale }) {
  const l = (en: string, vi: string) => localized(locale, en, vi); const steps = [l("Get your dog’s attention in a quiet space.", "Thu hút sự chú ý của chó ở nơi yên tĩnh."), l("Hold a treat close to the nose.", "Giữ đồ thưởng gần mũi."), l("Move the treat slowly upward.", "Từ từ đưa đồ thưởng lên trên."), l("When your dog sits naturally, mark the behavior.", "Khi chó tự nhiên ngồi xuống, đánh dấu hành vi."), l("Reward immediately.", "Thưởng ngay lập tức."), l("Repeat in short, upbeat sessions.", "Lặp lại trong các buổi ngắn, vui vẻ.")]; const [done, setDone] = useState(0); const [success, setSuccess] = useState(7); const [started, setStarted] = useState(false);
  return <main className="container lesson-page"><div className="lesson-title"><p className="eyebrow">{l("Training academy · Puppy foundations", "Học viện huấn luyện · Nền tảng chó con")}</p><h1>{l("Teach your dog to sit", "Dạy chó ngồi")}</h1><p>{l("Objective: build a clear, comfortable sit cue using reward-based practice.", "Mục tiêu: xây tín hiệu ngồi rõ ràng, thoải mái bằng luyện tập có thưởng.")}</p><div className="fact-chips"><span>{l("Beginner", "Cơ bản")}</span><span>3–5 {l("minutes", "phút")}</span><span>{l("Treats + quiet room", "Đồ thưởng + phòng yên tĩnh")}</span></div></div><div className="lesson-layout"><section><h2>{l("Step by step", "Từng bước")}</h2>{steps.map((x, i) => <button className={`step-row ${i < done ? "done" : ""} ${i === done ? "current" : ""}`} key={x} onClick={() => started && setDone(Math.max(done, i + 1))}><span>{i < done ? "✓" : i + 1}</span><p>{x}</p></button>)}</section><aside className="session-card"><p className="eyebrow">{l("Live session", "Buổi tập trực tiếp")}</p><div className="session-ring"><b>{success}</b><span>/ 10</span></div><p>{l("successful attempts", "lần thành công")}</p><div className="session-actions"><button className="button primary" onClick={() => { setStarted(true); if (done < steps.length) setDone(done + 1); }}>{started ? l("Complete step", "Hoàn thành bước") : l("Start session", "Bắt đầu buổi tập")}</button><button onClick={() => setSuccess(Math.min(10, success + 1))}>+ {l("Record success", "Ghi nhận thành công")}</button><button>{l("Record difficulty", "Ghi nhận khó khăn")}</button></div><div className="stop-note"><b>{l("When to stop", "Khi nào nên dừng")}</b><p>{l("Pause if your dog disengages, shows stress, or stops taking treats. End on an easy win.", "Tạm dừng nếu chó mất tập trung, căng thẳng hoặc không nhận đồ thưởng. Kết thúc bằng một thành công dễ.")}</p></div></aside></div></main>;
}

function Behavior({ locale }: { locale: Locale }) {
  const l = (en: string, vi: string) => localized(locale, en, vi); const [mood, setMood] = useState("Relaxed"); const [query, setQuery] = useState("");
  return <><PageHero locale={locale} route="/behavior" /><main className="container"><div className="food-search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder={l("Search licking, hiding, tail wagging…", "Tìm liếm chân, trốn, vẫy đuôi…")} /></div><div className="behavior-grid">{behaviorItems.filter(x => x.toLowerCase().includes(query.toLowerCase())).map((x, i) => <a href={x === "Licking paws" ? "/behavior/paw-licking" : "/behavior"} key={x}><span>{i < 10 ? l("Dog", "Chó") : l("Cat", "Mèo")}</span><h3>{x}</h3><b>→</b></a>)}</div><Section eyebrow={l("Body language guide", "Hướng dẫn ngôn ngữ cơ thể")} title={l("Read signals together", "Đọc các tín hiệu cùng nhau")} intro={l("One ear, tail or glance rarely tells the whole story.", "Một chiếc tai, cái đuôi hay ánh nhìn hiếm khi nói lên toàn bộ câu chuyện.")}><div className="body-guide"><div className="mood-tabs">{["Relaxed", "Playful", "Nervous", "Fearful", "Defensive", "Overstimulated"].map(x => <button className={mood === x ? "active" : ""} onClick={() => setMood(x)} key={x}>{x}</button>)}</div><div className="signal-card"><div className="pet-silhouette">{mood === "Relaxed" ? "◡" : mood === "Playful" ? "↝" : "◔"}</div><div><p className="eyebrow">{mood}</p><h2>{l("Look from eyes to tail", "Quan sát từ mắt đến đuôi")}</h2><div className="signal-grid">{[["Eyes", "Mắt"], ["Ears", "Tai"], ["Mouth", "Miệng"], ["Tail", "Đuôi"], ["Posture", "Tư thế"], ["Fur", "Lông"]].map(x => <button key={x[0]}><b>{l(x[0], x[1])}</b><span>{l("View clue", "Xem tín hiệu")}</span></button>)}</div></div></div></div></Section></main></>;
}

function PawLicking({ locale }: { locale: Locale }) {
  const l = (en: string, vi: string) => localized(locale, en, vi); const groups = [["Normal behavior", "Hành vi bình thường", "Occasional cleaning or grooming after being outside."], ["Environment", "Môi trường", "Dirt, mild irritation or something caught between the toes."], ["Emotional / behavioral", "Cảm xúc / hành vi", "Boredom, stress or a repetitive habit."], ["Health-related possibilities", "Khả năng liên quan sức khỏe", "Allergies, skin irritation, pain or injury can also contribute."]];
  return <><header className="article-hero container"><p className="eyebrow">{l("Behavior guide · Dogs", "Hướng dẫn hành vi · Chó")}</p><h1>{l("Why does my dog lick its paws?", "Vì sao chó liếm bàn chân?")}</h1><p>{l("Context matters. Notice frequency, intensity, timing and what else has changed.", "Bối cảnh rất quan trọng. Hãy để ý tần suất, mức độ, thời điểm và những thay đổi khác.")}</p></header><main className="container article-layout"><article><div className="explanation-grid">{groups.map((g, i) => <section key={g[0]}><span>0{i + 1}</span><h2>{l(g[0], g[1])}</h2><p>{g[2]}</p></section>)}</div><div className="vet-callout"><span aria-hidden="true">!</span><div><h2>{l("When should I contact a veterinarian?", "Khi nào nên liên hệ bác sĩ thú y?")}</h2><p>{l("Seek advice if licking is persistent or sudden, or if you notice swelling, bleeding, broken skin, limping, discharge, a strong odor, pain or marked behavior change. This guide cannot diagnose the cause.", "Hãy xin tư vấn nếu liếm dai dẳng hoặc đột ngột, hay có sưng, chảy máu, trầy da, đi khập khiễng, tiết dịch, mùi mạnh, đau hoặc thay đổi hành vi rõ rệt. Hướng dẫn này không thể chẩn đoán nguyên nhân.")}</p></div></div></article><aside><Status tone="neutral">{l("Pawtome Guidance", "Hướng dẫn Pawtome")}</Status><h3>{l("Observe before you explain", "Quan sát trước khi giải thích")}</h3><ul><li>{l("Which paw?", "Chân nào?")}</li><li>{l("After walks or at rest?", "Sau khi đi dạo hay lúc nghỉ?")}</li><li>{l("Occasional or hard to interrupt?", "Thỉnh thoảng hay khó ngắt?")}</li><li>{l("Any visible skin change?", "Có thay đổi da nhìn thấy?")}</li></ul><div className="community"><b>{l("Community Experience", "Trải nghiệm cộng đồng")}</b><p>“{l("Rinsing paws after muddy walks helped us notice when the pattern changed.", "Rửa chân sau khi đi bùn giúp chúng tôi nhận ra khi thói quen thay đổi.")}”</p><button>{l("Helpful", "Hữu ích")} · 42</button></div></aside></main></>;
}

function Care({ locale }: { locale: Locale }) {
  const l = (en: string, vi: string) => localized(locale, en, vi); const routine = [["07:00", "Wake + toilet", "Thức dậy + đi vệ sinh"], ["07:15", "Breakfast", "Bữa sáng"], ["07:45", "Morning walk", "Đi dạo sáng"], ["12:30", "Short activity", "Hoạt động ngắn"], ["17:30", "Main exercise", "Vận động chính"], ["19:00", "Dinner", "Bữa tối"], ["21:00", "Training / play", "Huấn luyện / chơi"], ["22:30", "Final toilet break", "Đi vệ sinh lần cuối"]]; const [checks, setChecks] = useState<string[]>(["water", "meal"]);
  return <><PageHero locale={locale} route="/care" /><main className="container care-layout"><section><div className="routine-controls"><select><option>Momo · Shiba Inu</option></select><select><option>{l("Adult", "Trưởng thành")}</option><option>{l("Puppy", "Chó con")}</option><option>{l("Senior", "Cao tuổi")}</option></select><select><option>{l("Medium activity", "Vận động vừa")}</option></select></div><div className="timeline">{routine.map((r, i) => <div key={r[0]}><time>{r[0]}</time><span /><div><b>{l(r[1], r[2])}</b><small>{i === 4 ? l("45–60 minutes", "45–60 phút") : l("Suggested time · editable", "Thời gian gợi ý · có thể sửa")}</small></div><button aria-label={l("Edit time", "Sửa giờ")}>•••</button></div>)}</div></section><aside className="checklist"><p className="eyebrow">{l("Today’s care", "Chăm sóc hôm nay")}</p><h2>{l("Five quiet essentials", "Năm điều thiết yếu")}</h2>{[["water", "Fresh water", "Nước sạch"], ["meal", "Meals", "Bữa ăn"], ["exercise", "Exercise", "Vận động"], ["behavior", "Behavior observation", "Quan sát hành vi"], ["toilet", "Toilet observation", "Quan sát vệ sinh"]].map(x => <label key={x[0]}><input type="checkbox" checked={checks.includes(x[0])} onChange={() => setChecks(checks.includes(x[0]) ? checks.filter(y => y !== x[0]) : [...checks, x[0]])} /><span>{l(x[1], x[2])}</span></label>)}<div className="progress"><span style={{ width: `${checks.length * 20}%` }} /></div><p>{checks.length} / 5 {l("complete", "đã xong")}</p><hr /><h3>{l("Weekly rhythm", "Nhịp hằng tuần")}</h3><p>{l("Coat · Ears · Paws · Bedding · Grooming", "Lông · Tai · Chân · Đệm nằm · Chải lông")}</p><h3>{l("Monthly rhythm", "Nhịp hằng tháng")}</h3><p>{l("Nails · Weight · Prevention · Equipment", "Móng · Cân nặng · Phòng ngừa · Thiết bị")}</p></aside></main></>;
}

function Grooming({ locale }: { locale: Locale }) {
  const l = (en: string, vi: string) => localized(locale, en, vi); const [coat, setCoat] = useState("Double coat");
  return <><PageHero locale={locale} route="/grooming" /><main className="container"><div className="coat-tabs">{["Short coat", "Double coat", "Long coat", "Curly coat", "Wire coat", "Hairless"].map(x => <button className={coat === x ? "active" : ""} onClick={() => setCoat(x)} key={x}>{x}</button>)}</div><div className="groom-hero"><div><p className="eyebrow">{coat}</p><h2>{l("Protect the coat—don’t fight it.", "Bảo vệ bộ lông—đừng chống lại nó.")}</h2><p>{l("For a double coat, brush to lift loose undercoat without damaging healthy guard hairs. Avoid routine shaving unless a veterinarian recommends it for a specific reason.", "Với lông hai lớp, chải để lấy lông tơ rụng mà không làm hỏng lớp lông bảo vệ. Tránh cạo thường xuyên trừ khi bác sĩ thú y khuyên vì lý do cụ thể.")}</p></div><div className="groom-stats"><span><small>{l("Brush", "Chải")}</small><b>2–3× / {l("week", "tuần")}</b></span><span><small>{l("Bath", "Tắm")}</small><b>6–8 {l("weeks", "tuần")}</b></span><span><small>{l("Shedding", "Rụng lông")}</small><b>{l("High · seasonal", "Nhiều · theo mùa")}</b></span></div></div><div className="season-grid">{[["Summer", "Mùa hè", "Hydration · cool walks · hot pavement · parasites"], ["Winter", "Mùa đông", "Cold tolerance · paw protection · coat needs"], ["Rainy season", "Mùa mưa", "Dry coats · rinse paws · watch skin · parasites"]].map(x => <article key={x[0]}><span aria-hidden="true">{x[0] === "Summer" ? "☀" : x[0] === "Winter" ? "❄" : "☂"}</span><h2>{l(x[0], x[1])}</h2><p>{x[2]}</p><a href="/care">{l("View seasonal guide", "Xem hướng dẫn theo mùa")} →</a></article>)}</div><div className="mistake-strip"><b>{l("Common mistake", "Lỗi thường gặp")}</b><p>{l("More bathing is not always better. Overwashing can dry skin and disrupt the coat.", "Tắm nhiều hơn không phải lúc nào cũng tốt. Tắm quá mức có thể làm khô da và ảnh hưởng bộ lông.")}</p></div></main></>;
}

function Safety({ locale }: { locale: Locale }) {
  const l = (en: string, vi: string) => localized(locale, en, vi); const [room, setRoom] = useState("Kitchen"); const hazards: Record<string, string[]> = { Kitchen: ["Chocolate", "Medicines", "Cleaning products", "Trash", "Cooked bones", "Sharp objects"], "Living Room": ["Loose cables", "Small batteries", "Open windows", "Unstable furniture"], Bedroom: ["Medicines", "Hair ties", "Essential oils", "Open windows"], Bathroom: ["Cleaning products", "Medicines", "Razors", "Standing water"], Garden: ["Toxic plants", "Fertilizer", "Pesticides", "Open gates"], Garage: ["Antifreeze", "Tools", "Rodent poison", "Vehicle access"] };
  return <><PageHero locale={locale} route="/safety" /><main className="container"><section className="emergency"><div><p className="eyebrow">{l("Emergency guide", "Hướng dẫn khẩn cấp")}</p><h2>{l("Some signs should not wait.", "Một số dấu hiệu không nên chờ đợi.")}</h2><p>{l("Difficulty breathing, collapse, severe bleeding, seizures, suspected poisoning, severe trauma or heatstroke signs require prompt professional veterinary care.", "Khó thở, ngã quỵ, chảy máu nghiêm trọng, co giật, nghi ngộ độc, chấn thương nặng hoặc dấu hiệu sốc nhiệt cần được chăm sóc thú y chuyên môn ngay.")}</p></div><a className="button light" href="tel:000">{l("Call your local emergency vet", "Gọi cơ sở thú y cấp cứu địa phương")}</a></section><Section eyebrow={l("Interactive home check", "Kiểm tra nhà tương tác")} title={l("Pet-proof your home", "Làm nhà an toàn cho thú cưng")}><div className="room-layout"><div className="room-tabs">{Object.keys(hazards).map(x => <button className={room === x ? "active" : ""} onClick={() => setRoom(x)} key={x}>{x}</button>)}</div><div className="room-card"><div className="room-art"><span>{room.slice(0, 1)}</span></div><div><p className="eyebrow">{room}</p><h3>{l("Potential hazards", "Nguy cơ tiềm ẩn")}</h3><ul>{hazards[room].map(x => <li key={x}><span>!</span>{x}</li>)}</ul></div></div></div></Section></main></>;
}

function Plants({ locale }: { locale: Locale }) {
  const l = (en: string, vi: string) => localized(locale, en, vi); const [query, setQuery] = useState(""); const items = [["Lilies", "danger", "Cats", "Highly dangerous; urgent veterinary care is needed after possible exposure."], ["Monstera", "caution", "Cats & dogs", "Can cause oral irritation, drooling and discomfort."], ["Sago palm", "danger", "Cats & dogs", "All parts are dangerous, especially the seeds."], ["Aloe vera", "avoid", "Cats & dogs", "Keep out of reach; ingestion may cause illness."], ["Spider plant", "safe", "Cats & dogs", "Generally considered non-toxic, but chewing can still upset digestion."], ["Chocolate", "danger", "Dogs & cats", "Risk depends on type, amount and pet size; seek prompt advice."], ["Grapes / raisins", "danger", "Dogs", "Potentially dangerous even when the amount seems small."], ["Onion / garlic", "danger", "Cats & dogs", "Fresh, cooked and powdered forms can be harmful."], ["Xylitol", "danger", "Dogs", "A veterinary emergency for dogs."]] as const;
  return <><PageHero locale={locale} route="/plants" /><main className="container"><div className="food-search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder={l("Search Monstera, lilies, chocolate…", "Tìm Monstera, hoa ly, sô-cô-la…")} /></div><div className="toxin-grid">{items.filter(x => x[0].toLowerCase().includes(query.toLowerCase())).map(x => <article key={x[0]}><div><span className="plant-mark">{x[0].slice(0, 1)}</span><Status tone={x[1] as Tone} /></div><h2>{x[0]}</h2><p className="kicker">{x[2]}</p><p>{x[3]}</p></article>)}</div><div className="urgent-note wide"><b>{l("Suspected exposure?", "Nghi ngờ tiếp xúc?")}</b><p>{l("Do not wait for symptoms or induce vomiting unless a veterinary professional tells you to. Contact a veterinarian or animal poison service promptly and keep the packaging or plant sample.", "Không chờ triệu chứng hoặc tự gây nôn trừ khi chuyên gia thú y hướng dẫn. Hãy liên hệ bác sĩ thú y hoặc dịch vụ chống độc động vật ngay và giữ lại bao bì hay mẫu cây.")}</p></div></main></>;
}

function FirstDays({ locale }: { locale: Locale }) {
  const l = (en: string, vi: string) => localized(locale, en, vi); const stages = [["Days 1–3", "Ngày 1–3", "Adjustment and a safe, quiet environment.", "Thích nghi và môi trường yên tĩnh, an toàn."], ["Week 1", "Tuần 1", "Establish a predictable routine.", "Thiết lập nề nếp dễ đoán."], ["Week 2", "Tuần 2", "Begin gentle foundation training.", "Bắt đầu huấn luyện nền tảng nhẹ nhàng."], ["Week 3", "Tuần 3", "Controlled, positive socialization.", "Xã hội hóa có kiểm soát, tích cực."], ["Week 4", "Tuần 4", "Review habits, health and behavior.", "Rà soát thói quen, sức khỏe và hành vi."]]; const [done, setDone] = useState<number[]>([0]);
  return <><PageHero locale={locale} route="/first-30-days" /><main className="container thirty-days"><div className="month-progress"><b>{done.length} / 5</b><span>{l("milestones complete", "cột mốc hoàn thành")}</span><div className="progress"><i style={{ width: `${done.length * 20}%` }} /></div></div><div className="stage-list">{stages.map((s, i) => <article className={done.includes(i) ? "complete" : ""} key={s[0]}><button aria-label={l("Toggle complete", "Đánh dấu hoàn thành")} onClick={() => setDone(done.includes(i) ? done.filter(x => x !== i) : [...done, i])}>{done.includes(i) ? "✓" : i + 1}</button><div><p className="eyebrow">{l(s[0], s[1])}</p><h2>{l(s[2], s[3])}</h2><ul><li>{l("Keep introductions small and calm", "Giới thiệu từ từ và bình tĩnh")}</li><li>{l("Watch appetite, toileting and rest", "Theo dõi ăn uống, vệ sinh và nghỉ ngơi")}</li><li>{l("Let trust set the pace", "Để niềm tin quyết định nhịp độ")}</li></ul></div></article>)}</div></main></>;
}

function Ask({ locale }: { locale: Locale }) {
  const l = (en: string, vi: string) => localized(locale, en, vi); const [input, setInput] = useState(""); const [asked, setAsked] = useState(false);
  function submit(e: FormEvent) { e.preventDefault(); if (input.trim()) setAsked(true); }
  return <><PageHero locale={locale} route="/ask" /><main className="container ask-shell"><section className="chat"><div className="assistant-message"><div className="assistant-avatar">P</div><div><p>{l("Hi—what would you like to understand about your pet today?", "Chào bạn—hôm nay bạn muốn hiểu điều gì về thú cưng?")}</p><small><span>✓</span>{l("Based on Pawtome Care Library", "Dựa trên Thư viện Chăm sóc Pawtome")}</small></div></div>{asked && <><div className="user-message">{input}</div><div className="assistant-message"><div className="assistant-avatar">P</div><div><Status tone="neutral">{l("Food Safety", "An toàn thực phẩm")}</Status><p>{l("Watermelon flesh can be an occasional treat for many dogs when served plain, seedless and without rind. Start with a small piece. Avoid sweetened products.", "Phần thịt dưa hấu có thể là món ăn vặt thỉnh thoảng cho nhiều chó khi dùng nguyên chất, bỏ hạt và vỏ. Bắt đầu với một miếng nhỏ. Tránh sản phẩm có đường.")}</p><p><b>{l("Contact a veterinarian", "Liên hệ bác sĩ thú y")}</b> {l("if your pet is unwell, ate a large amount, or swallowed rind. This is general guidance, not a diagnosis.", "nếu thú cưng không khỏe, ăn lượng lớn hoặc nuốt vỏ. Đây là hướng dẫn chung, không phải chẩn đoán.")}</p><small><span>✓</span>{l("Reviewed Pawtome guidance · Related: Food Safety", "Hướng dẫn Pawtome đã rà soát · Liên quan: An toàn thực phẩm")}</small></div></div></>}<form onSubmit={submit}><label className="sr-only" htmlFor="ask-input">{l("Ask a question", "Đặt câu hỏi")}</label><textarea id="ask-input" value={input} onChange={e => { setInput(e.target.value); setAsked(false); }} placeholder={l("Ask about Momo, food, training or behavior…", "Hỏi về Momo, thực phẩm, huấn luyện hoặc hành vi…")} /><button type="submit" aria-label={l("Send", "Gửi")}>↑</button></form><div className="prompt-row">{[l("Can Momo eat watermelon?", "Momo ăn dưa hấu được không?"), l("How do I improve recall?", "Làm sao cải thiện gọi về?"), l("Why does my cat hide?", "Vì sao mèo trốn?")].map(x => <button onClick={() => { setInput(x); setAsked(false); }} key={x}>{x}</button>)}</div></section><aside><h3>{l("Trusted path", "Lộ trình tin cậy")}</h3>{[l("Reviewed pet knowledge", "Kiến thức đã rà soát"), l("Momo’s profile", "Hồ sơ của Momo"), l("Relevant rules", "Quy tắc phù hợp"), l("Plain-language guidance", "Hướng dẫn dễ hiểu")].map((x, i) => <div key={x}><span>{i + 1}</span><p>{x}</p></div>)}<hr /><p className="fineprint">{l("Ask Pawtome does not act as a veterinarian and cannot diagnose illness.", "Hỏi Pawtome không thay thế bác sĩ thú y và không thể chẩn đoán bệnh.")}</p></aside></main></>;
}

function MyPets({ locale }: { locale: Locale }) {
  const l = (en: string, vi: string) => localized(locale, en, vi);
  const [userId,setUserId]=useState<string|null>(null); const [pets,setPets]=useState<Array<{id:string;name:string}>>([]); const [name,setName]=useState(""); const [message,setMessage]=useState("");
  useEffect(()=>{const client=createSupabaseBrowserClient();if(!client)return;async function load(){const auth=await client!.auth.getUser();if(!auth.data.user)return;setUserId(auth.data.user.id);const result=await client!.from("pets").select("id,name").eq("owner_id",auth.data.user.id).order("created_at");if(result.data)setPets(result.data);}void load();},[]);
  async function addPet(event:FormEvent){event.preventDefault();const client=createSupabaseBrowserClient();if(!client||!userId||!name.trim())return;const {data,error}=await client.from("pets").insert({owner_id:userId,name:name.trim()}).select("id,name").single();if(error)setMessage(error.message);else{setPets(current=>[...current,data]);setName("");setMessage(l("Pet saved privately.","Đã lưu thú cưng ở chế độ riêng tư."));}}
  async function addPhoto(petId:string,file:File|undefined){if(!file)return;try{await uploadPetPhoto(petId,file);setMessage(l("Private photo uploaded.","Đã tải ảnh riêng tư."));}catch(error){setMessage(error instanceof Error?error.message:l("Upload failed.","Tải lên thất bại."));}}
  return <><PageHero locale={locale} route="/my-pets" /><main className="container">{!userId&&<div className="review-note"><Status tone="neutral">{l("Demo profile", "Hồ sơ minh họa")}</Status><p>{l("Sign in to persist private pets, photos, favorites, care tasks, weights and training progress with Row Level Security.","Đăng nhập để lưu riêng tư thú cưng, ảnh, mục yêu thích, việc chăm sóc, cân nặng và tiến độ huấn luyện bằng Row Level Security.")} <a href="/account"><b>{l("Sign in", "Đăng nhập")} →</b></a></p></div>}<a href="/my-pets/momo" className="pet-profile-card"><img src={breedImages["Shiba Inu"]} alt="Momo the Shiba Inu" /><div><Status tone="neutral">{l("Preserved demo animal", "Thú minh họa được giữ lại")}</Status><h2>Momo</h2><p>Shiba Inu · {l("Born 12 May 2023", "Sinh 12 tháng 5, 2023")} · 9.5 kg</p><div className="fact-chips"><span>{l("Medium activity", "Vận động vừa")}</span><span>{l("Intermediate training", "Huấn luyện trung cấp")}</span></div></div><b>→</b></a>{userId&&<section className="private-pets"><h2>{l("Private pet profiles", "Hồ sơ thú cưng riêng tư")}</h2>{pets.map(pet=><article key={pet.id}><div><Status tone="safe">{l("Private", "Riêng tư")}</Status><h3>{pet.name}</h3></div><label className="button secondary">{l("Add private photo", "Thêm ảnh riêng tư")}<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>void addPhoto(pet.id,event.target.files?.[0])}/></label></article>)}<form className="add-pet-form" onSubmit={addPet}><label><span>{l("Pet name", "Tên thú cưng")}</span><input required maxLength={80} value={name} onChange={event=>setName(event.target.value)}/></label><button className="button primary">{l("Add pet", "Thêm thú cưng")}</button></form>{message&&<p role="status">{message}</p>}</section>}</main></>;
}

function Account({ locale }: { locale: Locale }) {
  const l=(en:string,vi:string)=>localized(locale,en,vi); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [message,setMessage]=useState(""); const [signedIn,setSignedIn]=useState(false);
  useEffect(()=>{const client=createSupabaseBrowserClient();if(!client)return;async function load(){const auth=await client!.auth.getUser();setSignedIn(Boolean(auth.data.user));}void load();},[]);
  async function submit(event:FormEvent,mode:"sign-in"|"sign-up"){event.preventDefault();const client=createSupabaseBrowserClient();if(!client){setMessage(l("Supabase environment variables are not configured.","Chưa cấu hình biến môi trường Supabase."));return;}const result=mode==="sign-in"?await client.auth.signInWithPassword({email,password}):await client.auth.signUp({email,password,options:{data:{locale}}});if(result.error)setMessage(result.error.message);else{setSignedIn(Boolean(result.data.user));setMessage(mode==="sign-in"?l("Signed in.","Đã đăng nhập."):l("Account created. Check email if confirmation is enabled.","Đã tạo tài khoản. Kiểm tra email nếu bật xác nhận."));}}
  async function signOut(){const client=createSupabaseBrowserClient();if(client)await client.auth.signOut();setSignedIn(false);setMessage(l("Signed out.","Đã đăng xuất."));}
  return <><PageHero locale={locale} route="/account" tag={l("Supabase Auth", "Xác thực Supabase")}/><main className="container account-shell">{signedIn?<section><Status tone="safe">{l("Authenticated", "Đã xác thực")}</Status><h2>{l("Your private Pawtome space is ready.","Không gian Pawtome riêng tư đã sẵn sàng.")}</h2><div className="actions"><a className="button primary" href="/my-pets">{l("Open my pets", "Mở thú cưng")}</a><button className="button secondary" onClick={()=>void signOut()}>{l("Sign out", "Đăng xuất")}</button></div></section>:<form onSubmit={event=>void submit(event,"sign-in")}><label><span>Email</span><input required type="email" autoComplete="email" value={email} onChange={event=>setEmail(event.target.value)}/></label><label><span>{l("Password", "Mật khẩu")}</span><input required minLength={8} type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)}/></label><div className="actions"><button className="button primary" type="submit">{l("Sign in", "Đăng nhập")}</button><button className="button secondary" type="button" onClick={event=>void submit(event,"sign-up")}>{l("Create account", "Tạo tài khoản")}</button></div></form>}{message&&<p role="status">{message}</p>}</main></>;
}

function Momo({ locale }: { locale: Locale }) {
  const l = (en: string, vi: string) => localized(locale, en, vi); const [weight, setWeight] = useState([9.1, 9.2, 9.3, 9.4, 9.5]); const [tasks, setTasks] = useState([true, true, false, false, true]);
  return <main><header className="dashboard-hero"><div className="container"><div><p className="eyebrow">{l("Momo’s day · Friday", "Ngày của Momo · Thứ Sáu")}</p><h1>{l("Good morning, Momo & Tung.", "Chào buổi sáng, Momo & Tùng.")}</h1><p>{l("A calm overview of care, progress and what comes next.", "Tổng quan nhẹ nhàng về chăm sóc, tiến bộ và việc tiếp theo.")}</p></div><img src={breedImages["Shiba Inu"]} alt="Momo the Shiba Inu" /></div></header><div className="container dashboard-grid"><section className="today-card"><p className="eyebrow">{l("Today’s overview", "Tổng quan hôm nay")}</p><h2>{tasks.filter(Boolean).length} / 5 {l("complete", "đã xong")}</h2>{[["Morning walk", "Đi dạo sáng"], ["Breakfast", "Bữa sáng"], ["Training session", "Buổi huấn luyện"], ["Evening walk", "Đi dạo tối"], ["Fresh water", "Nước sạch"]].map((x, i) => <label key={x[0]}><input type="checkbox" checked={tasks[i]} onChange={() => setTasks(tasks.map((v, n) => n === i ? !v : v))} /><span>{l(x[0], x[1])}</span></label>)}</section><section className="stat-grid">{[["9.5 kg", "Current weight", "Cân nặng hiện tại"], ["6 days", "Training streak", "Chuỗi huấn luyện"], ["5 days", "Next grooming", "Lần chăm lông tới"]].map(x => <article key={x[1]}><b>{x[0]}</b><span>{l(x[1], x[2])}</span></article>)}</section><section className="weight-card"><div><p className="eyebrow">{l("Weight tracking", "Theo dõi cân nặng")}</p><h2>{l("A steady view, not a medical conclusion", "Quan sát ổn định, không phải kết luận y tế")}</h2></div><div className="weight-chart" aria-label={l("Weight history bar chart", "Biểu đồ lịch sử cân nặng")}>{weight.map((x, i) => <div key={i}><span style={{ height: `${(x - 8.7) * 100}px` }} /><b>{x}</b><small>{["Jan", "Feb", "Mar", "Apr", "May", "Jun"][i]}</small></div>)}</div><button onClick={() => setWeight([...weight, Number((weight[weight.length - 1] + 0.1).toFixed(1))])}>＋ {l("Add weight entry", "Thêm cân nặng")}</button></section><section className="activity-card"><p className="eyebrow">{l("Recent timeline", "Dòng thời gian gần đây")}</p>{[["May 01", "Weight — 9.5 kg"], ["Apr 18", "Grooming"], ["Mar 03", "Training milestone — Reliable Sit"], ["Feb 12", "Vaccination"], ["Jan 10", "Weight — 9.1 kg"]].map(x => <div key={x[0]}><time>{x[0]}</time><span /><p>{x[1]}</p></div>)}</section><section className="personal-card"><p className="eyebrow">{l("Personalized for Momo", "Cá nhân hóa cho Momo")}</p><h2>{l("Training suggestions for Momo", "Gợi ý huấn luyện cho Momo")}</h2><p>{l("Short recall games and calm door-wait practice based on Momo’s age, breed profile and recent progress.", "Trò chơi gọi về ngắn và luyện chờ cửa bình tĩnh dựa trên tuổi, hồ sơ giống và tiến bộ gần đây của Momo.")}</p><a href="/training">{l("View suggestions", "Xem gợi ý")} →</a></section></div></main>;
}

function Saved({ locale, saved, toggleSaved }: { locale: Locale; saved: string[]; toggleSaved: (s: string) => void }) {
  const l = (en: string, vi: string) => localized(locale, en, vi); const items = saved.length ? saved : ["Shiba Inu", "Strawberry guide", "Teach your dog to sit", "Paw licking"];
  return <><PageHero locale={locale} route="/saved" /><main className="container"><div className="saved-tabs"><button className="active">{l("All", "Tất cả")}</button><button>{l("Breeds", "Giống")}</button><button>{l("Guides", "Hướng dẫn")}</button><button>{l("Food", "Thực phẩm")}</button><button>{l("Training", "Huấn luyện")}</button></div><div className="saved-grid">{items.map((x, i) => <article key={x}><div className={`saved-art art-${i % 4}`}>{x.slice(0, 1)}</div><span className="kicker">{i % 2 ? l("Pawtome guide", "Hướng dẫn Pawtome") : l("Breed", "Giống")}</span><h2>{x}</h2><button onClick={() => toggleSaved(x)}>♥ {l("Saved", "Đã lưu")}</button></article>)}</div></main></>;
}

function Generic({ locale, route }: { locale: Locale; route: string }) {
  return <><PageHero locale={locale} route={route} /><main className="container empty-page"><h2>{localized(locale, "A thoughtful guide is ready here.", "Hướng dẫn hữu ích đã sẵn sàng tại đây.")}</h2><a className="button primary" href="/discover">{localized(locale, "Explore Pawtome", "Khám phá Pawtome")}</a></main></>;
}

export default function PawtomeApp({ route, catalogEntries, catalogSource, catalogWarning }: { route: string; catalogEntries: AnimalEntry[]; catalogSource: "supabase" | "seed"; catalogWarning: string | null }) {
  const [locale, setLocale] = useState<Locale>("en-US"); const [menu, setMenu] = useState(false); const [searchOpen, setSearchOpen] = useState(false); const [search, setSearch] = useState(""); const [saved, setSaved] = useState<string[]>([]);
  useEffect(() => { const previous = window.localStorage.getItem("pawtome-locale") as Locale | null; const fav = window.localStorage.getItem("pawtome-saved"); queueMicrotask(()=>{if (previous) setLocale(previous);if (fav) setSaved(JSON.parse(fav));}); const client = createSupabaseBrowserClient(); if (!client) return; async function load(){const auth=await client!.auth.getUser();if(!auth.data.user)return;const result=await client!.from("favorites").select("target_key").eq("user_id",auth.data.user.id);if(result.data?.length)setSaved(result.data.map((item:{target_key:string})=>item.target_key));}void load(); }, []);
  function changeLocale(value: Locale) { setLocale(value); window.localStorage.setItem("pawtome-locale", value); document.documentElement.lang = value; }
  function toggleSaved(item: string) { const key=item.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""); setSaved(current => { const next = current.includes(item)||current.includes(key) ? current.filter(x => x !== item && x !== key) : [...current, key]; window.localStorage.setItem("pawtome-saved", JSON.stringify(next)); void persistFavorite("animal-entry",key,next.includes(key)); return next; }); }
  const l = (en: string, vi: string) => localized(locale, en, vi);
  const nav = [["Discover", "Khám phá", "/discover"], ["Breeds", "Giống", "/breeds"], ["Care", "Chăm sóc", "/care"], ["Food", "Thực phẩm", "/food"], ["Training", "Huấn luyện", "/training"], ["Behavior", "Hành vi", "/behavior"], ["My Pets", "Thú cưng", "/my-pets"]];
  const searchResults = [
    ...catalogEntries.slice(0,10).map(entry=>[l(...groupLabels[entry.group]),localizeCatalog(entry.commonName,locale),`/breeds/${entry.slug}`]), ["Food", "Strawberry", "/food/strawberry"], ["Training", "Teach your dog to sit", "/training/sit"], [l("Behavior", "Hành vi"), l("Why dogs lick their paws", "Vì sao chó liếm chân"), "/behavior/paw-licking"]
  ].filter(x => !search || x[1].toLowerCase().includes(search.toLowerCase()));
  let content: ReactNode;
  if (route === "/") content = <Home locale={locale} saved={saved} toggleSaved={toggleSaved} />;
  else if (route === "/discover") content = <Discover locale={locale} />;
  else if (route === "/breeds") content = <Breeds locale={locale} saved={saved} toggleSaved={toggleSaved} entries={catalogEntries} source={catalogSource} warning={catalogWarning} />;
  else if (route.startsWith("/breeds/")) { const entry=catalogEntries.find(item=>`/breeds/${item.slug}`===route); content=entry?<AnimalDetail locale={locale} entry={entry}/>:<Generic locale={locale} route={route}/>; }
  else if (route === "/compare") content = <Compare locale={locale} />;
  else if (route === "/pet-match") content = <PetMatch locale={locale} />;
  else if (route === "/food") content = <Food locale={locale} />;
  else if (route === "/food/strawberry") content = <Strawberry locale={locale} />;
  else if (route === "/food/checker") content = <IngredientChecker locale={locale} />;
  else if (route === "/training") content = <Training locale={locale} />;
  else if (route === "/training/sit") content = <SitLesson locale={locale} />;
  else if (route === "/behavior") content = <Behavior locale={locale} />;
  else if (route === "/behavior/paw-licking") content = <PawLicking locale={locale} />;
  else if (route === "/care") content = <Care locale={locale} />;
  else if (route === "/grooming") content = <Grooming locale={locale} />;
  else if (route === "/safety") content = <Safety locale={locale} />;
  else if (route === "/plants") content = <Plants locale={locale} />;
  else if (route === "/first-30-days") content = <FirstDays locale={locale} />;
  else if (route === "/ask") content = <Ask locale={locale} />;
  else if (route === "/my-pets") content = <MyPets locale={locale} />;
  else if (route === "/my-pets/momo") content = <Momo locale={locale} />;
  else if (route === "/account") content = <Account locale={locale} />;
  else if (route === "/saved") content = <Saved locale={locale} saved={saved} toggleSaved={toggleSaved} />;
  else content = <Generic locale={locale} route={route} />;

  return <div className="app-shell"><a className="skip-link" href="#main">{l("Skip to content", "Bỏ qua đến nội dung")}</a><nav className="topbar"><div className="nav-inner"><a className="brand" href="/" aria-label="Pawtome home"><span>Paw</span>tome<i /></a><div className={`main-nav ${menu ? "open" : ""}`}>{nav.map(x => <a className={route === x[2] || (x[2] !== "/discover" && route.startsWith(x[2])) ? "active" : ""} href={x[2]} key={x[2]}>{l(x[0], x[1])}</a>)}</div><div className="nav-actions"><button className="icon-button" onClick={() => setSearchOpen(!searchOpen)} aria-label={l("Search", "Tìm kiếm")}>⌕</button><label className="locale-select"><span className="sr-only">{l("Language", "Ngôn ngữ")}</span><select value={locale} onChange={e => changeLocale(e.target.value as Locale)}><option value="vi">VI</option><option value="en-US">EN US</option><option value="en-GB">EN UK</option></select></label><a className="ask-button" href="/ask">{l("Ask Pawtome", "Hỏi Pawtome")}</a><button className="menu-button" aria-expanded={menu} onClick={() => setMenu(!menu)}><span /><span /></button></div></div>{searchOpen && <div className="global-search"><div className="container"><label><span>⌕</span><input autoFocus value={search} onChange={e => setSearch(e.target.value)} placeholder={l("Search all Pawtome", "Tìm toàn bộ Pawtome")} /><button onClick={() => setSearchOpen(false)}>×</button></label><div>{searchResults.map(x => <a href={x[2]} key={x[2]}><small>{x[0]}</small><b>{x[1]}</b><span>→</span></a>)}</div></div></div>}</nav><div id="main">{content}</div><nav className="mobile-bottom"><a href="/"><span>⌂</span>{l("Home", "Trang chủ")}</a><a href="/discover"><span>⌕</span>{l("Discover", "Khám phá")}</a><a className="ask" href="/ask"><span>✦</span>{l("Ask", "Hỏi")}</a><a href="/saved"><span>♡</span>{l("Saved", "Đã lưu")}</a><a href="/my-pets"><span>●</span>{l("My Pets", "Thú cưng")}</a></nav><footer><div className="container footer-grid"><div><a className="brand light-brand" href="/"><span>Paw</span>tome<i /></a><p>{l("Understand. Care. Grow Together.", "Thấu hiểu. Chăm sóc. Cùng trưởng thành.")}</p></div><div><b>{l("Explore", "Khám phá")}</b><a href="/breeds">{l("Breeds", "Giống")}</a><a href="/food">{l("Food safety", "An toàn thực phẩm")}</a><a href="/behavior">{l("Behavior", "Hành vi")}</a></div><div><b>{l("Care", "Chăm sóc")}</b><a href="/training">{l("Training", "Huấn luyện")}</a><a href="/grooming">{l("Grooming", "Chăm sóc lông")}</a><a href="/safety">{l("Emergency guide", "Hướng dẫn khẩn cấp")}</a></div><div><b>{l("Important", "Quan trọng")}</b><p>{l("Pawtome offers general education, not veterinary diagnosis. For emergencies, contact a veterinary professional.", "Pawtome cung cấp kiến thức chung, không chẩn đoán thú y. Khi khẩn cấp, hãy liên hệ chuyên gia thú y.")}</p></div></div></footer></div>;
}
